apiVersion: v2
description: A Helm chart for deploying Automatisch
name: automatisch
version: 0.4.1
# renovate: datasource=docker depName=automatischio/automatisch
appVersion: "0.10.0"
annotations:
  artifacthub.io/links: |
    - name: Application
      url: https://automatisch.io/
sources:
  - https://github.com/CloudTooling/k8s-automatisch
keywords:
- zapier
- automatisch
- automation