# Default values for Automatisch chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  storageClass: ""
  accessMode: ReadWriteOnce
replicaCount: 2
# -- Update policy
updateStrategy: "RollingUpdate"
image:
  repository: automatischio/automatisch
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # renovate: datasource=docker depName=automatischio/automatisch
  tag: "0.12.0"
persistence:
  volumeSize: 3Gi
postgresql:
  enabled: true
  # @ignore, Configure pod security context
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  # @ignore, Configure security context
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: false
    # Hardening
    capabilities:
      drop: ["ALL"]
    seccompProfile:
      type: "RuntimeDefault"
  # see https://artifacthub.io/packages/helm/bitnami/postgresql?modal=values
  auth:
    database: automatisch
    username: automatischUser
    password:
    postgresPassword:
  persistence:
    volumeSize: 5Gi
  primary:
    persistence:
      # @ignored -- internal configuration
      existingClaim: automatisch-postgresql-0
    resources: {}
  metrics:
    enabled: false
    resources: {}
redis:
  enabled: true
  # @ignore, Configure pod security context
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  # @ignore, Configure security context
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: false
    # Hardening
    capabilities:
      drop: ["ALL"]
    seccompProfile:
      type: "RuntimeDefault"
  # renovate: datasource=docker depName=redis
  version: "7.2.2"
  # @ignore, Configure resource limits
  resources: {}
  persistence:
    volumeSize: 3Gi

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
# @ignore, Configure pod security context
podSecurityContext:
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 3000
  fsGroup: 2000
# @ignore, Configure security context
securityContext:
  runAsUser: 0
  runAsNonRoot: false
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
  # Hardening
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: "RuntimeDefault"

ingress:
  enabled: false
  className: ""
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hostname: ""
  tls: []

app:
  # -- Seed configuration, only done once!
  seed:
    # -- admin user to configure during installation
    admin:
      # -- Admin User
      email: admin@automatisch.io
      fullName: Admin User
  config:
    # -- Automatisch Environment
    APP_ENV: production
    # -- Can be used to configure log level such as error, warn, info, http, debug
    LOG_LEVEL: info
    # -- HTTP Protocol
    PROTOCOL: http
    # -- Don't use hardcoded initial admin user by default, see [here](https://automatisch.co/docs/advanced-configuration#disable-seed-user) for more information
    DISABLE_SEED_USER: true
  credentials:
    # -- Encryption Key to store credentials
    ENCRYPTION_KEY:
    # -- Webhook Secret Key to verify webhook requests
    WEBHOOK_SECRET_KEY:
    # -- Secret Key to authenticate the user
    APP_SECRET_KEY:
# @ignore, Configure resource limits
resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
