apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ah.fullname" . }}
  labels:
    {{- include "ah.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: {{ .Values.updateStrategy }}
    {{- if eq .Values.updateStrategy "RollingUpdate"}}
    rollingUpdate:
      maxSurge: "100%"
      maxUnavailable: "50%"
    {{- end }}
  selector:
    matchLabels:
      {{- include "ah.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        # used to detect config changes to trigger update
        {{- $configApp := printf "%s-%s" $.Values.app.config $.Values.app.credentials }}
        {{- $configIngress := printf "%s" $.Values.ingress.hostname  }}
        checksum/config: {{ printf "%s-%s" $configApp $configIngress | sha256sum }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ah.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ah.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: main
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORT
              value: "3000"
            - name: HOST
              value: "localhost"
            {{- include "ah.envValues" . | nindent 12 }}
          ports:
            - name: ah-tcp
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: "/automatisch/storage"
              name: storage
            - mountPath: "/home/node/.cache"
              name: cache
            - mountPath: "/tmp"
              name: tmp
            - mountPath: "/automatisch/logs"
              name: logs
        - name: worker
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: WORKER
              value: "true"
            {{- include "ah.envValues" . | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: "/automatisch/storage"
              name: storage
            - mountPath: "/home/node/.cache"
              name: cache
            - mountPath: "/tmp"
              name: tmp
            - mountPath: "/automatisch/logs"
              name: logs
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "ah.fullname" . }}
        - name: cache
          emptyDir:
            sizeLimit: 100Mi
        - name: tmp
          emptyDir:
            sizeLimit: 100Mi
        - name: logs
          emptyDir:
            sizeLimit: 300Mi
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}