{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ah.serviceAccountName" . }}
  labels:
    {{- include "ah.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ah.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ah.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
