apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ah.fullname" . }}
  labels:
    {{- include "ah.labels" . | nindent 4 }}
stringData:
  {{- range $k, $v := .Values.app.credentials }}
  {{ include "ah.camelcase" $k }}: {{ $v }}
  {{- end }}
  dbName: "{{ .Values.postgres.config.dbName }}"
  dbUser: "{{ .Values.postgres.config.dbUser }}"
  dbPassword: "{{ .Values.postgres.config.dbPassword }}"