apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ah.fullname" . }}
  labels:
    {{- include "ah.labels" . | nindent 4 }}
stringData:
  {{- range $k, $v := .Values.app.credentials }}
  {{ include "ah.camelcase" $k }}: {{ $v }}
  {{- end }}
  dbHost: "{{ include "ah.fullname" . }}-postgresql"
  dbName: "{{ .Values.postgresql.config.dbName }}"
  dbUser: "{{ .Values.postgresql.auth.username }}"
  dbPassword: "{{ .Values.postgresql.auth.password }}"