{{- if .Values.postgres.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ah.fullname" . }}-postgres
  labels:
    {{- include "ah.postgresLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres-tcp
      protocol: TCP
      name: postgres
  selector:
    {{- include "ah.postgresSelectorLabels" . | nindent 4 }}
 {{- end }}